create database customer_project;
use customer_project;
select * from cleaned_data
limit 20;
#1)what is the total revenue generated by male vs . female customers?
select gender, SUM(purchase_amount) as revenue
from cleaned_data
group by gender
#2) which customers used a discount but still spent more than the average review rating?
select customer_id, purchase_Amount
from cleaned_data
where discount_applied = 'yes' and purchase_amount >= (select avg (purchase_amount) from cleaned_data)
#Q3.which are the top 5 products with the highest average review rating?
SELECT item_purcahsed, ROUND(AVG(review_rating::numeric),2) as "Avereage Product Rating"
from cleaned_data
group  by item_purchased
order by avg(review_rating) desc
limit 5;
## 4)compare teh average purchase amounts between standard and express shipping
select shipping_type,
round(AVG(purchase_amount),2)
from cleaned_data
where shipping_type in ('standard','Express')
group by shipping_type
##Q5. Do subscribed customers spend more? Compare average spend and total revenue
##between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from cleaned_data
group by subscription_status
order by total_revenue, avg_spend desc;
##Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from cleaned_data
group by item_purchased
order by discount_rate desc
limit 5;
###Q7. Segment customers into New, Returning, and Loyal based on their total
##number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from cleaned_data
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment
##Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from cleaned_data
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
##Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from cleaned_data
where previous_purchases > 5
group by subscription_status
##Q10. What is the revenue contribution of each age group?
select aged_group,
SUM(purchase_amount) as total_revenue
from cleaned_data
group by aged_group
order by total_revenue desc;
select * from cleaned_data;